MAIL_SENDER: "please-change-me-at-config-initializers-devise@example.com"
SECRET_KEY_BASE: 3feb1a4a6608fcaa5676809f8c4080b71f6e2fe27a62775ebe694206a2499bc0b7a1d56c2a790ec91b97f6c4e585fdb1aba96cb7df03b144f4696a882a855143
SECRET_TOKEN: sdadhasdhoaUDPOAkdaKD;Akdakdas
AWS_ACCESS_KEY_ID: AKIAISG4WYR6DURQJ3CQ
AWS_SECRET_ACCESS_KEY: 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
BUCKET: "chat-live"
S3_HOST_NAME: "s3.amazonaws.com"
AWS_REGION: "ap-southeast-1"

#figaro heroku:set -e production